#pragma once
#include "lvgl.h"
LV_IMAGE_DECLARE(gui_glyph_0_48);
LV_IMAGE_DECLARE(gui_glyph_0_49);
LV_IMAGE_DECLARE(gui_glyph_0_50);
LV_IMAGE_DECLARE(gui_glyph_0_51);
LV_IMAGE_DECLARE(gui_glyph_0_52);
LV_IMAGE_DECLARE(gui_glyph_0_53);
LV_IMAGE_DECLARE(gui_glyph_0_54);
LV_IMAGE_DECLARE(gui_glyph_0_55);
LV_IMAGE_DECLARE(gui_glyph_0_56);
LV_IMAGE_DECLARE(gui_glyph_0_57);
LV_IMAGE_DECLARE(gui_glyph_0_46);
LV_IMAGE_DECLARE(gui_glyph_0_45);
extern const lv_image_dsc_t *const gui_digits_0[12];
LV_IMAGE_DECLARE(gui_glyph_1_48);
LV_IMAGE_DECLARE(gui_glyph_1_49);
LV_IMAGE_DECLARE(gui_glyph_1_50);
LV_IMAGE_DECLARE(gui_glyph_1_51);
LV_IMAGE_DECLARE(gui_glyph_1_52);
LV_IMAGE_DECLARE(gui_glyph_1_53);
LV_IMAGE_DECLARE(gui_glyph_1_54);
LV_IMAGE_DECLARE(gui_glyph_1_55);
LV_IMAGE_DECLARE(gui_glyph_1_56);
LV_IMAGE_DECLARE(gui_glyph_1_57);
LV_IMAGE_DECLARE(gui_glyph_1_46);
LV_IMAGE_DECLARE(gui_glyph_1_45);
extern const lv_image_dsc_t *const gui_digits_1[12];
LV_IMAGE_DECLARE(gui_glyph_2_48);
LV_IMAGE_DECLARE(gui_glyph_2_49);
LV_IMAGE_DECLARE(gui_glyph_2_50);
LV_IMAGE_DECLARE(gui_glyph_2_51);
LV_IMAGE_DECLARE(gui_glyph_2_52);
LV_IMAGE_DECLARE(gui_glyph_2_53);
LV_IMAGE_DECLARE(gui_glyph_2_54);
LV_IMAGE_DECLARE(gui_glyph_2_55);
LV_IMAGE_DECLARE(gui_glyph_2_56);
LV_IMAGE_DECLARE(gui_glyph_2_57);
LV_IMAGE_DECLARE(gui_glyph_2_46);
LV_IMAGE_DECLARE(gui_glyph_2_45);
extern const lv_image_dsc_t *const gui_digits_2[12];
LV_IMAGE_DECLARE(gui_glyph_3_48);
LV_IMAGE_DECLARE(gui_glyph_3_49);
LV_IMAGE_DECLARE(gui_glyph_3_50);
LV_IMAGE_DECLARE(gui_glyph_3_51);
LV_IMAGE_DECLARE(gui_glyph_3_52);
LV_IMAGE_DECLARE(gui_glyph_3_53);
LV_IMAGE_DECLARE(gui_glyph_3_54);
LV_IMAGE_DECLARE(gui_glyph_3_55);
LV_IMAGE_DECLARE(gui_glyph_3_56);
LV_IMAGE_DECLARE(gui_glyph_3_57);
LV_IMAGE_DECLARE(gui_glyph_3_46);
LV_IMAGE_DECLARE(gui_glyph_3_45);
extern const lv_image_dsc_t *const gui_digits_3[12];
LV_IMAGE_DECLARE(gui_text_art);
LV_IMAGE_DECLARE(gui_eyes_art);
LV_IMAGE_DECLARE(gui_ring_art);
LV_IMAGE_DECLARE(gui_plus_art);
LV_IMAGE_DECLARE(gui_corners_art);
LV_IMAGE_DECLARE(gui_food_art);
LV_IMAGE_DECLARE(gui_food_char_33529);
LV_IMAGE_DECLARE(gui_food_char_26524);
